# Generated by Django 4.2.17 on 2025-01-13 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mlmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Time', models.FloatField(default=0)),
                ('V1', models.FloatField(default=0)),
                ('V2', models.FloatField(default=0)),
                ('V3', models.FloatField(default=0)),
                ('V4', models.FloatField(default=0)),
                ('V5', models.FloatField(default=0)),
                ('V6', models.FloatField(default=0)),
                ('V7', models.FloatField(default=0)),
                ('V8', models.FloatField(default=0)),
                ('V9', models.FloatField(default=0)),
                ('V10', models.FloatField(default=0)),
                ('V11', models.FloatField(default=0)),
                ('V12', models.FloatField(default=0)),
                ('V13', models.FloatField(default=0)),
                ('V14', models.FloatField(default=0)),
                ('V15', models.FloatField(default=0)),
                ('V16', models.FloatField(default=0)),
                ('V17', models.FloatField(default=0)),
                ('V18', models.FloatField(default=0)),
                ('V19', models.FloatField(default=0)),
                ('V20', models.FloatField(default=0)),
                ('V21', models.FloatField(default=0)),
                ('V22', models.FloatField(default=0)),
                ('V23', models.FloatField(default=0)),
                ('V24', models.FloatField(default=0)),
                ('V25', models.FloatField(default=0)),
                ('V26', models.FloatField(default=0)),
                ('V27', models.FloatField(default=0)),
                ('V28', models.FloatField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlmodels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
